name: Update Pi-hole Blocklist

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'config.json'
      - 'convert_lists.py'

jobs:
  update-lists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run list converter
      run: |
        python convert_lists.py
    
    - name: Check for changes
      id: changes
      run: |
        if [ -f pihole_list.txt ]; then
          if git diff --quiet pihole_list.txt; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
        else
          echo "No output file generated"
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pihole_list.txt summary.json
        git commit -m "Update Pi-hole blocklist - $(date '+%Y-%m-%d %H:%M:%S UTC')"
        git push
    
    - name: Create release
      if: steps.changes.outputs.changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v$(date +%Y%m%d-%H%M%S)
        name: Pi-hole Blocklist Update $(date '+%Y-%m-%d %H:%M:%S UTC')
        body: |
          ## Updated Pi-hole Blocklist
          
          This release contains an updated Pi-hole blocklist generated from multiple reputable sources.
          
          ### Changes:
          - Updated blocklist with latest domains
          - Generated on: $(date '+%Y-%m-%d %H:%M:%S UTC')
          
          ### Usage:
          Add this URL to your Pi-hole configuration:
          ```
          https://raw.githubusercontent.com/${{ github.repository }}/main/pihole_list.txt
          ```
          
          ### Sources:
          This list is compiled from 22+ reputable ad-blocking sources including:
          - AdGuard DNS filter
          - AdAway Default Blocklist
          - Dan Pollock's List
          - OISD Blocklist
          - And many more...
        files: |
          pihole_list.txt
          summary.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update README stats
      if: steps.changes.outputs.changed == 'true'
      run: |
        if [ -f summary.json ]; then
          DOMAIN_COUNT=$(python -c "import json; data=json.load(open('summary.json')); print(data['total_domains'])")
          echo "Updating README with domain count: $DOMAIN_COUNT"
          # This would update the README with current stats
        fi
